services:
  postgres:
    image: postgres:16
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-chatdb}
      POSTGRES_USER: ${POSTGRES_USER:-chat_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-chat_password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  chat-storage:
    build: .
    depends_on:
      - postgres
    env_file: .env
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL:-jdbc:postgresql://postgres:5432/chatdb}
      LOG_DIR: /var/log/chatstorage
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/var/log/chatstorage
    restart: unless-stopped
    logging:
     driver: json-file
     options:
      max-size: "10m"
      max-file: "5

  adminer:
    image: adminer:4
    restart: always
    depends_on:
      - postgres
    ports:
      - "8081:8080"

volumes:
  postgres_data:
