spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/chatdb}
    username: ${SPRING_DATASOURCE_USERNAME:chat_user}
    password: ${SPRING_DATASOURCE_PASSWORD:chat_password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful

logging:
  config: classpath:log4j2-spring.xml
  level:
    root: INFO
    com.example.chatstorage: INFO

security:
  api-key-secret: ${SECURITY_API_KEY_SECRET:chatstorage}
  key-expiration-ms: ${KEY_EXPIRATION_MS:60000}

ratelimit:
  requests-per-minute: ${RATE_LIMIT_REQUESTS_PER_MINUTE:10}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
